clusterName: eks-cluster

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::127214183643:role/eks-alb-controller-role

region: us-east-1

vpcId: vpc-0a8282d767880cb70
