apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-routing
  namespace: monitoring
  labels:
    release: monitoring
spec:
  route:
    receiver: telegram-receiver
    groupBy: ["alertname", "namespace"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    matchers:
      - name: namespace
        value: monitoring
        matchType: =

  receivers:
    - name: telegram-receiver
      webhookConfigs:
        - url: http://telegram-webhook.monitoring.svc:8080/alerts

    - name: default-receiver
