apiVersion: v1
kind: Secret
metadata:
  name: telegram-webhook-secret
  namespace: monitoring
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "8685948220:AAHcUUBR8Cn9pznDKhsIYN0k8PM3g9VCwjE"
  TELEGRAM_CHAT_ID: "8398271222"
