apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-load-balancer-controller/app.yaml
  - sample-app/app.yaml
  - flask-app/app.yaml
  - monitoring-chart/app.yaml
  - monitoring-resources/app.yaml
  - telegram-alerts/app.yaml
